version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ALLOW_ORIGINS=http://localhost:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secret
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server --requirepass secret
