version: "3.11.2"

services:
  app:
    build: .
    ports:
      - 80:80
    environment:
      - REDIS_HOST=os.environ.get('REDIS_HOST')
      - REDIS_PORT=os.environ.get('REDIS_PORT')
      - REDIS_PASSWORD=os.environ.get('REDIS_PASSWORD')
      - ALLOW_ORIGINS=http://localhost:3000
    depends_on:
      - redis

  redis:
    image: redis
    command: redis-server --requirepass your_redis_password
    ports:
      - 6379:6379